<?php

namespace App\Http\Controllers;

use App\Jobs\SendAbsentParentNotification;
use App\Models\Attendance;
use App\Models\QrAttendanceToken;
use App\Repositories\AttendanceRepository;
use App\Traits\SchoolSession;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Interfaces\SchoolSessionInterface;

class QrAttendanceController extends Controller
{
    use SchoolSession;

    /** We need the trait's helper, so inject a minimal session repo. */
    protected $schoolSessionRepository;

    public function __construct(SchoolSessionInterface $schoolSessionRepository)
    {
        $this->schoolSessionRepository = $schoolSessionRepository;
        $this->middleware(['auth'])->except(['scan']);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Teacher: manage QR tokens
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * GET /attendance/qr
     * List today's tokens generated by the authenticated teacher.
     */
    public function index()
    {
        $this->authorize('take attendances');

        $tokens = QrAttendanceToken::with(['schoolClass', 'section', 'course'])
            ->where('teacher_id', auth()->id())
            ->whereDate('date', today())
            ->latest()
            ->get();

        return view('attendances.qr.index', compact('tokens'));
    }

    /**
     * GET /attendance/qr/create
     * Form to choose class / course / validity window.
     */
    public function create(Request $request)
    {
        $this->authorize('take attendances');

        $sessionId        = $this->getSchoolCurrentSession();
        $classesAndSections = \App\Models\SchoolClass::with('sections')
            ->whereHas('promotions', fn($q) => $q->where('session_id', $sessionId))
            ->orderBy('class_name')
            ->get();

        $courses = \App\Models\Course::where('session_id', $sessionId)->orderBy('name')->get();

        return view('attendances.qr.create', compact('classesAndSections', 'courses', 'sessionId'));
    }

    /**
     * POST /attendance/qr
     * Generate a new QR token.
     */
    public function store(Request $request)
    {
        $this->authorize('take attendances');

        $validated = $request->validate([
            'class_id'      => 'required|integer|exists:school_classes,id',
            'section_id'    => 'nullable|integer',
            'course_id'     => 'nullable|integer',
            'valid_minutes' => 'required|integer|min:0|max:1440',
            'school_start'  => 'required|date_format:H:i',
        ]);

        $sessionId = $this->getSchoolCurrentSession();

        $token = QrAttendanceToken::create([
            'teacher_id'    => auth()->id(),
            'class_id'      => $validated['class_id'],
            'section_id'    => $validated['section_id']    ?? 0,
            'course_id'     => $validated['course_id']     ?? 0,
            'session_id'    => $sessionId,
            'date'          => today()->toDateString(),
            'token'         => QrAttendanceToken::generateToken(),
            'valid_minutes' => $validated['valid_minutes'],
            'school_start'  => $validated['school_start'] . ':00',
            'is_active'     => true,
        ]);

        return redirect()->route('attendance.qr.show', $token->id)
            ->with('status', 'QR code generated. Share it with students to scan.');
    }

    /**
     * GET /attendance/qr/{id}
     * Display a single QR token (large QR image + status + scanned-student list).
     */
    public function show(int $id)
    {
        $this->authorize('take attendances');

        $token = QrAttendanceToken::with(['schoolClass', 'section', 'course'])
            ->where('teacher_id', auth()->id())
            ->findOrFail($id);

        // Students who have already scanned (attendance marked today for this token's class)
        $scanned = Attendance::with('student')
            ->where('class_id',   $token->class_id)
            ->where('session_id', $token->session_id)
            ->whereDate('date',   $token->date)
            ->where('status',     'on')
            ->get();

        return view('attendances.qr.show', compact('token', 'scanned'));
    }

    /**
     * DELETE /attendance/qr/{id}
     * Revoke / deactivate a token.
     */
    public function destroy(int $id)
    {
        $this->authorize('take attendances');

        $token = QrAttendanceToken::where('teacher_id', auth()->id())->findOrFail($id);
        $token->update(['is_active' => false]);

        return back()->with('status', 'QR token deactivated.');
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Student: scan endpoint (no auth guard — accessible from mobile browser)
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * GET /attendance/scan/{token}
     * Student opens this URL after scanning the QR code.
     * Must be authenticated (student logs in on their phone); redirects to login if not.
     */
    public function scan(string $tokenStr)
    {
        // Require authentication for the scan endpoint
        if (! auth()->check()) {
            return redirect()->route('login')
                ->with('status', 'Please log in to mark your attendance.');
        }

        $token = QrAttendanceToken::where('token', $tokenStr)->first();

        // Token not found
        if (! $token) {
            return view('attendances.qr.result', [
                'success' => false,
                'message' => 'Invalid QR code. Please ask your teacher to regenerate.',
            ]);
        }

        // Token expired or deactivated
        if (! $token->isValid()) {
            return view('attendances.qr.result', [
                'success' => false,
                'message' => 'This QR code has expired or been deactivated. Ask your teacher for a new one.',
            ]);
        }

        $student = auth()->user();

        // Only students can self-scan
        if (! $student->isStudent()) {
            return view('attendances.qr.result', [
                'success' => false,
                'message' => 'Only students can use the QR attendance scan.',
            ]);
        }

        // Prevent double-marking
        $alreadyMarked = Attendance::where('student_id', $student->id)
            ->where('class_id',   $token->class_id)
            ->where('session_id', $token->session_id)
            ->whereDate('date',   $token->date)
            ->exists();

        if ($alreadyMarked) {
            return view('attendances.qr.result', [
                'success' => true,
                'message' => 'Your attendance was already recorded for today.',
            ]);
        }

        // Calculate late_minutes
        $lateMinutes = $token->calcLateMinutes();

        // Mark attendance
        Attendance::create([
            'student_id'   => $student->id,
            'class_id'     => $token->class_id,
            'section_id'   => $token->section_id,
            'course_id'    => $token->course_id,
            'session_id'   => $token->session_id,
            'date'         => $token->date->toDateString(),
            'status'       => 'on',
            'late_minutes' => $lateMinutes,
            'check_in'     => now()->format('H:i:s'),
        ]);

        $message = $lateMinutes > 0
            ? "You have been marked present (late by {$lateMinutes} minute(s))."
            : 'You have been marked present. Have a great day!';

        return view('attendances.qr.result', [
            'success'     => true,
            'message'     => $message,
            'lateMinutes' => $lateMinutes,
        ]);
    }
}
